# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: interestelar_api_development

test:
  <<: *default
  database: interestelar_api_test

# Heroku maneja la conexión automáticamente con DATABASE_URL
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>